env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  ecmaFeatures:
    generators: true

  ecmaVersion: 12
plugins:
  - "@typescript-eslint"
rules:
  {
    quote: [1, "single", { "avoidEscape": true }],
    spaced-comment: "off",
    no-console: "warn",
    consistent-return: "off",
    func-names: "off",
    object-shorthand: "off",
    no-process-exit: "off",
    no-param-reassign: "off",
    no-return-await: "off",
    no-underscore-dangle: "off",
    class-methods-use-this: "off",
    prefer-destructuring: ["error", { "object": true, "array": false }],
    no-unused-vars: ["error", { "argsIgnorePattern": "req|res|next|val" }],
  }
